# Generated by Django 3.1.2 on 2020-11-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehaviouralAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct', models.IntegerField(default=0)),
                ('punctuality', models.IntegerField(default=0)),
                ('dedication', models.IntegerField(default=0)),
                ('participation', models.IntegerField(default=0)),
                ('hospitality', models.IntegerField(default=0)),
                ('neatness', models.IntegerField(default=0)),
                ('creativity', models.IntegerField(default=0)),
                ('physical', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
        ),
    ]
