# Generated by Django 3.1.2 on 2020-12-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_studentbehaviouralassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signs')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentclass')),
            ],
        ),
    ]
