# Generated by Django 3.1.2 on 2020-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='classs',
            field=models.CharField(max_length=100),
        ),
    ]
