# Generated by Django 3.1.2 on 2020-12-11 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20201211_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='image',
            new_name='t_image',
        ),
        migrations.AddField(
            model_name='signature',
            name='p_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='signs'),
            preserve_default=False,
        ),
    ]
